Fix _alloc_page_aligned_pinned_view()
Pin the host buffer in case of an accelerator is present. It can
fix the issue of "RuntimeError: level_zero backend failed with
error: 20 (UR_RESULT_ERROR_DEVICE_LOST)" during running
"pytest tests/benchmarks/test_xpu_connector_benchmark.py".

Also add fallback mechanism to ensure torch tensor allocation
succeed in case device does not support pinned memory allocation.

Signed-off-by: Zhan Xue <zhan.xue@intel.com>