[CI/Build] Remove obsolete vLLM patch from Docker build
- Docker build file has a patch currently for vllm, but seems vllm fixed it in recent release and hence it breaks the docker build:

```
 => ERROR [vllm-openai 6/6] RUN patch /usr/local/lib/python3.12/dist-packages/vllm/dis  0.3s
------
 > [vllm-openai 6/6] RUN patch /usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py     /usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.patch:
0.206 patching file /usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py
0.206 Hunk #1 FAILED at 1069.
0.206 1 out of 1 hunk FAILED -- saving rejects to file /usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py.rej
------
Dockerfile:98
--------------------
  97 |     
  98 | >>> RUN patch /usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py \
  99 | >>>     /usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.patch
 100 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c patch /usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py     /usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.patch" did not complete successfully: exit code: 1
```

- Removing the patch, which is obsolete fixes the build